fn main() {
    panic!();  //~ ERROR panic!(..) statement might be reachable
}
